spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ktb_community
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

server:
  tomcat:
    max-http-form-post-size: 10GB

springdoc:
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴

security:
  jwt:
    token:
      expire-length: 999999999999999
      secret-key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
logging:
  level:
    root: info